### ISSUE TITLE
Dual-language OCR

### ISSUE THREAD

**Issue by jaseg** [A9T9/Free-OCR-Robot#3]
Hi,
for bilingual texts (say, language textbooks) a dual-language mode would be great. If necessary, I can provide some german/japanese and english/japanese test data.

Thanks for the great work!

**Comment by A9T9** [comment]
The OCR tool uses the new Microsoft OCR engine, which does not (yet?) support bilingual texts. But Asian languages OCR supports the western alphabet as well (at least kind of).
