### ISSUE TITLE
Japanese does not seem to work in the web frontend

### ISSUE THREAD

**Issue by jaseg** [A9T9/Free-OCR-Robot#4]
When submitting a smartphone image of bilingual german/japanese text to the web OCR service set to "Japanese", the german parts are recognized almost flawlessly, but none of the chinese or japanese characters are. This does not seem to be an issue of the OCR engine since after selecting "Chinese Traditional", the chinese characters are recognized very well (but (obviously) the german is garbled and japanese hiragana are still not recognized).

**Comment by A9T9** [comment]
I confirmed the issue and will fix it asap. As you said, it is not the OCR engine but the web front-end. Thanks for reporting it!

**Comment by A9T9** [comment]
fixed
